<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>eCedula Receipt {{ $application->tracking_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #0f2a2e; font-size: 12px; }
        .header { border-bottom: 3px solid #0d7377; padding-bottom: 12px; margin-bottom: 20px; }
        .brand { font-size: 28px; font-weight: bold; color: #0d7377; letter-spacing: 1px; }
        .sub { color: #5a6b6e; margin-top: 4px; }
        .row { margin-bottom: 6px; }
        .label { color: #5a6b6e; width: 160px; display: inline-block; }
        table { width: 100%; border-collapse: collapse; margin-top: 18px; }
        th, td { padding: 8px 10px; border-bottom: 1px solid #d7e2e3; text-align: left; }
        th { background: #e8f4f4; }
        .total { font-size: 16px; font-weight: bold; }
        .qr { text-align: center; margin-top: 24px; }
        .footer { margin-top: 28px; font-size: 10px; color: #7a8a8c; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">eCedula</div>
        <div class="sub">Community Tax Certificate — Official Transaction Receipt</div>
    </div>

    <div class="row"><span class="label">Tracking No.</span> <strong>{{ $application->tracking_number }}</strong></div>
    <div class="row"><span class="label">Applicant</span> {{ $application->applicantName() }}</div>
    <div class="row"><span class="label">Email</span> {{ $application->email }}</div>
    <div class="row"><span class="label">Delivery Mode</span> {{ str_replace('_', ' ', $application->delivery_mode) }}</div>
    <div class="row"><span class="label">Barangay</span> {{ $application->barangay?->name }}</div>
    <div class="row"><span class="label">Status</span> {{ str_replace('_', ' ', $application->status) }}</div>
    <div class="row"><span class="label">Paid At</span> {{ optional($application->paid_at)->format('M d, Y h:i A') ?? '—' }}</div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align:right">Amount (PHP)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Basic Community Tax</td>
                <td style="text-align:right">{{ number_format($application->base_tax, 2) }}</td>
            </tr>
            <tr>
                <td>Additional Community Tax</td>
                <td style="text-align:right">{{ number_format($application->additional_tax, 2) }}</td>
            </tr>
            <tr>
                <td>Late Interest ({{ $application->interest_months }} mo.)</td>
                <td style="text-align:right">{{ number_format($application->interest_amount, 2) }}</td>
            </tr>
            <tr>
                <td>Delivery Fee</td>
                <td style="text-align:right">{{ number_format($application->delivery_fee, 2) }}</td>
            </tr>
            <tr>
                <td>Convenience Fee</td>
                <td style="text-align:right">{{ number_format($application->convenience_fee, 2) }}</td>
            </tr>
            <tr>
                <td>Server Fee</td>
                <td style="text-align:right">{{ number_format($application->server_fee, 2) }}</td>
            </tr>
            <tr>
                <td>Payment Processor Fee</td>
                <td style="text-align:right">{{ number_format($application->payment_processor_fee, 2) }}</td>
            </tr>
            <tr>
                <td class="total">Total Due</td>
                <td class="total" style="text-align:right">{{ number_format($application->total_due, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="qr">
        <img src="data:image/svg+xml;base64,{{ $qrBase64 }}" width="140" height="140" alt="QR">
        <div style="margin-top:8px;">Scan to view transaction online</div>
        <div style="font-size:10px;color:#5a6b6e;">{{ $trackUrl }}</div>
    </div>

    <div class="footer">
        This receipt was generated by eCedula. Soft copy certificates are available for soft-copy delivery mode after payment confirmation.
    </div>
</body>
</html>
